# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79cc2757d2987e8baf85f2f1a90e408156f954f8feb949aa4866716eee991feb95a5e5024eca95c58f243984da14e22e995c0fc1d7a49ea50770dacc98d81fcc

test:
  secret_key_base: df58b39683e0b8ad67ec7a5750117a7f5c8038e0c63f6f94231558348f10cb74cecaf9efbef9a0b9290f565c825bba0e4465566398216fd60ac15e7b3952d607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
